main: me.mattyhd0.chatcolor.ChatColorPlugin
name: 'ChatColor'
version: '${project.version}'
api-version: 1.13
description: 'A plugin that allows you to create color patterns for the chat'
author: MattyHD0, maiminhdung
softdepend: [PlaceholderAPI]
folia-supported: true
commands:
  chatcolor:
    description: ChatColor main command
    usage: /<command>
  chatcoloradmin:
    description: ChatColor admin command
    usage: /<command>